ecommerceproject/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('add/<int:prod_id>/',views.add_cart,name='add_cart'),
    path('',views.cart_detail,name='cart_detail'),
    path('remove/<int:prod_id>/',views.cart_remove,name='cart_remove'),
    path('delete/<int:prod_id>/', views.cart_delete, name='cart_delete'),

]

ecommerceproject/ecommerce/urls.py
from django.urls import path
from . import views

app_name='ecommerce'
urlpatterns = [
    path('',views.allProdCat,name='allProdCat'),
    path('<slug:slug>/',views.allProdCat,name='products_by_category'),
    path('<slug:c_slug>/<slug:p_slug>/',views.prodDetail,name='prodetail'),
]

ecommerceproject/ecommerceproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ecommerce/', include('ecommerce.urls')),
    path('search/', include('searchapp.urls')),
    path('cart/', include('cart.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

ecommerceproject/searchapp/urls.py
from django.urls import path
from . import views

app_name='searchapp'
urlpatterns = [
    path('',views.search,name='search'),
]

ecommerceproject/cart/models.py
from django.db import models
from ecommerce.models import Product,Category
# Create your models here.
class Cart(models.Model):
    cart_id = models.CharField(max_length=250,blank=True)
    date_added = models.DateField(auto_now_add=True)
    class Meta:
        db_table = 'Cart'
        ordering = ['date_added']

    def __str__(self):
        return '{}'.format(self.cart_id)

class CartItem(models.Model):
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)
    class Meta:
        db_table = 'CartItem'

    def sub_total(self):
        return  self.product.price*self.quantity

    def __str__(self):
        return '{}'.format(self.product)

ecommerceproject/ecommerce/models.py
from django.db import models
from django.urls import reverse
# Create your models here.

class Category(models.Model):
    cname = models.CharField(max_length=250,unique=True)
    slug = models.SlugField(max_length=250,unique=True)
    cdesc = models.TextField(blank=True)
    cimage = models.ImageField(upload_to='category',blank=True)

    class Meta:
        ordering=('cname',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return '{}'.format(self.cname)

    def get_url(self):
        return reverse('ecommerce:products_by_category',args=[self.slug])

class Product(models.Model):
    name = models.CharField(max_length=250,unique=True)
    slug = models.SlugField(max_length=250,unique=True)
    desc = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10,decimal_places=2)
    image = models.ImageField(upload_to='product',blank=True)
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    stock = models.IntegerField()
    balance = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now= True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def __str__(self):
        return '{}'.format(self.name)

    def get_url(self):
        return reverse('ecommerce:prodetail',args=[self.category.slug, self.slug])

ecommerceproject/searchapp/models.py
from django.db import models

# Create your models here.

ecommerceproject/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from ecommerce.models import Product
from .models import Cart,CartItem
from django.core.exceptions import ObjectDoesNotExist
# Create your views here.
def cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart

def add_cart(request,prod_id):
    product = Product.objects.get(id=prod_id)
    try:
        cart = Cart.objects.get(cart_id=cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(
            cart_id=cart_id(request)
        )
        cart.save()
    try:
        cart_item = CartItem.objects.get(product=product,cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(
            product=product,
            quantity=1,
            cart=cart
        )
        cart_item.save()
    return redirect('cart:cart_detail')

def cart_detail(request,total=0,counter=0,cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart,active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request, 'cart.html', dict(cart_items=cart_items, total=total, counter=counter))

def cart_remove(request,prod_id):
    cart = Cart.objects.get(cart_id=cart_id(request))
    product = get_object_or_404(Product,id=prod_id)
    cart_item = CartItem.objects.get(product=product,cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return  redirect('cart:cart_detail')

def cart_delete(request,prod_id):
    cart = Cart.objects.get(cart_id=cart_id(request))
    product = get_object_or_404(Product, id=prod_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

ecommerceproject/ecommerce/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from django.core.paginator import Paginator,EmptyPage,InvalidPage
# Create your views here.

def allProdCat(request,slug=None):
    c_page = None
    products_list = None
    if slug != None:
        c_page = get_object_or_404(Category,slug=slug)
        products_list = Product.objects.all().filter(category=c_page,balance=True)
    else:
        products_list = Product.objects.all().filter(balance=True)
    paginator = Paginator(products_list,3)
    try:
        page=int(request.GET.get('page','1'))
    except:
        page=1
    try:
        products = paginator.page(page)
    except (EmptyPage,InvalidPage):
        products = paginator.page(paginator.num_pages)

    return render(request,'category.html',{'category':c_page,'products':products})

def prodDetail(request,c_slug,p_slug):
    try:
        product=Product.objects.get(category__slug=c_slug,slug=p_slug)
    except Exception as e:
        raise e
    return render(request,'product.html',{'product':product})

ecommerceproject/searchapp/views.py
from django.shortcuts import render
from ecommerce.models import Product
from django.db.models import Q
# Create your views here.

def search(request):
    products = None
    query = None
    if 'q' in request.GET:
        query= request.GET.get('q')
        products = Product.objects.all().filter(Q(name__contains=query)| Q(desc__contains=query))
        return render(request,'search.html',{'query':query,'products':products})

ecommerceproject/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <title>{% block title %}{% endblock %}</title>
    <!-- CSS only -->
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" >
    <link href="{% static 'css/custom.css' %}" rel="stylesheet" >
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
<script src="https://kit.fontawesome.com/444ff38389.js" ></script>
</head>
<body>
<div>

{% include 'header.html' %}

{% include 'navbar.html' %}

{% block content %}
{% endblock %}
</div>

{% include 'footer.html' %}


    <script src="{% static 'js/popper.min.js' %}" ></script>
    <script src="{% static 'js/bootstrap.min.js' %}" ></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}" ></script>

</body>
</html>

ecommerceproject/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
        Please check Catalogue
{% endblock %}
{% block title %}
        Cart -STOCKTON CAFE
{% endblock %}
{% block content %}
{% if not cart_items %}
<div>
        <div class="text-center">
               <br>
                <h1 class="text-center my_title">
                        Your Shopping Cart is empty
                </h1>
                <br>
                <p class="text-center">
                        Please Click <a href="{% url 'ecommerce:allProdCat' %}">Here</a> to continue shopping


                </p>
        </div>
</div>
{% else %}
<div>
        <div class="text-center">
                <br>
                <h1 class="text-center my_title">
                        Your Shopping Cart
                </h1>
                <br>

        </div>
</div>
<div class="row mx-auto">
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
               <table class="table my_custom_table">
                   <thead class="my_custom_thead">
                   <tr>
                       <th colspan="5">
                           Your items
                       </th>

                   </tr>
                   </thead>
                   <tbody>
                   {% for cart_item in cart_items %}
                        <tr>
                            <td>
                                <a href="cart_item.product.get_absolute_url"><img class="float-left rounded custom_image" src="{{cart_item.product.image.url}}" alt="" style="width:100px;height:100px;"> </a>
                            </td>
                            <td class="text-left">
                                {{cart_item.product.name}}
                                <br>
                                SKU: {{cart_item.product.id}}
                                <br>
                                Price: ${{cart_item.product.price}}
                                <br>
                                Qty : {{cart_item.quantity}} x ${{cart_item.product.price}}

                            </td>
                            <td>
                                $ {{cart_item.sub_total}}
                            </td>
                            {% if cart_item.quantity < cart_item.product.stock %}
                            <td>
                                &nbsp;
                                <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a"> <i class="fa fa-plus custom_icon"></i></a>
                                &nbsp;
                                <a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-minus custom_icon"></i></a>
                                &nbsp;
                                <a href="{% url 'cart:cart_delete' cart_item.product.id %}" class="custom_icon"><i class="fa fa-trash custom_icon"></i></a>
                            </td>
                            {% else %}
                            <td>
                                &nbsp;
                                <a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-minus custom_icon"></i></a>
                                &nbsp;
                                <a href="{% url 'cart:cart_delete' cart_item.product.id %}" class="custom_icon"><i class="fa fa-trash custom_icon"></i></a>
                            </td>
                            {% endif %}

                        </tr>
                   {% endfor %}
                   </tbody>

               </table>
        </div>
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
            <tr>
                <th>
                    CHECKOUT
                </th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>
                    Please review your shopping cart items before proceeding with order payment
                </td>
            </tr>
            <tr>
                <td class="text-left">
                    Your Total is : <strong>$ {{ total }}</strong>
                </td>
            </tr>
            </tbody>
        </table>
        <div class="mx-auto">
            <a href="{% url 'ecommerce:allProdCat' %}" class="btn btn-secondary btn-block my_custom-button">
                Continue Shopping
            </a>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

ecommerceproject/templates/category.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
    {% if category %}
        {{ category.cdesc|truncatewords:150 }}
    {% else %}
        WELCOME TO STOCKTON CAFE
    {% endif %}
{% endblock %}

{% block title %}
    {% if category %}
        {{ category.cname }} -STOCKTON CAFE
    {% else %}
        SEE OUR NEW COLLECTIONS -STOCKTON CAFE
    {% endif %}
{% endblock %}

{% block content %}
<div class="container">
    {% if category %}
    <div>
        <div class="row my_row">
            <div class="mx-auto">
             <p><a href="{% url 'ecommerce:allProdCat' %}" >OUR PRODUCTS</a></p>
            </div>
        </div>
    </div>
    {% endif %}

    <div class="mx-auto">
         {% if category %}
        <div>
            <img class="my_image" src="{{category.cimage.url}}" alt="{{category.cname}}" >

             <h1 class="text-left my_title">{{category.cname}}</h1>
                <p class="text-justify">{{category.cdesc}}</p>
        </div>
        {% else %}
        <div align="center">

            <img  class="my_image_padding" src="{% static 'img/bannernew.png' %}" alt="{{category.cname}}" width="1200px" height="600px">
        </div><br>
        <div>
            <h1 class="text-center my_title">Our Product Collections</h1>
             <p class="text-justify">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five cen</p>
        </div>
        {% endif %}
    </div>
    <div  class="container">
        <div class="row mx-auto" >
            {% for products in products.object_list %}
            <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4" style="padding-bottom:50px;">
                <div class="card text-center" style="width:100%;height:100%;">
                    <a href="{{products.get_url}}"><img class="card-img-top my_image" src="{{products.image.url}}" alt="{{products.name}}" style="width:100%;"></a>
                    <div class="card-body">
                        <h4>{{products.name}}</h4>
                        <p>{{products.price}}</p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
        <div class="mx-auto" style="padding-bottom:50px;">
            {% if products.paginator.num_pages > 1 %}

            <hr>
             <div class="text-center">
                {% for pg in products.paginator.page_range %}
                <a href="?page={{ pg }}" class="btn btn-light btn-sm{% if products.number == pg %} active {% endif %}">{{ pg }}</a>
                 {% endfor %}
            </div>
             {% endif %}
        </div><br>
</div>
{% endblock %}

ecommerceproject/templates/footer.html
<div class="footer fixed-bottom my_footer">
    <p class="text-center">&copy; ABC tech pvt ltd.All rights Reserved</p>
</div>

ecommerceproject/templates/header.html
{% load static %}
<header>
    <center>
        <a href="{% url 'ecommerce:allProdCat' %}"><img src="{% static 'img/logonew.png' %}" alt="logoimage" width="100px" height="100px"></a>
    </center>
</header>

ecommerceproject/templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">

                        <a class="navbar-brand" href="#">THE STOCKTON CAFE</a>
                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                         <span class="navbar-toggler-icon"></span>
                        </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                             <ul class="navbar-nav">
                                <li class="nav-item">
                                 <a class="nav-link active" href="#">Home</a>
                                </li>
                                 <li class="nav-item dropdown {% if 'ecommerce' in request.path %} active {% endif %}">
                                     <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                  Catalogue
                                    </a>
                                 <ul class="dropdown-menu dropdown-menu" aria-labelledby="navbarDropdown">

                                  <li><a class="dropdown-item" href="{% url 'ecommerce:allProdCat' %}">All Products</a></li>
                                    {% for link in links %}
                                     <li><hr class="dropdown-divider"> </li>
                                     <li> <a class="dropdown-item" href="{{link.get_url}}">{{link.cname}}</a></li>

                                     {% endfor %}


                                 </ul>
                                 </li>

{% if item_count > 0 %}
                                 <li class="nav-item">
                                     <a class="nav-link" href="{% url 'cart:cart_detail' %}"><i class="fa fa-shopping-cart"></i>({{item_count}})</a>
                                 </li>
                                 {% endif %}
                             </ul>

                    </div>
                    <form class="d-flex" role="search" action="{% url 'searchapp:search' %}" method="get">
                        {% csrf_token %}
        <input name="q" class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit"><i class="fa fa-search"></i></button>
      </form>

    </nav>

ecommerceproject/templates/product.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
        {{ product.desc|truncatewords:150 }}
{% endblock %}

{% block title %}
        {{ product.name }} -STOCKTON CAFE
{% endblock %}

{% block content %}

<div class="row my_product_row_class">
    <div class="mx-auto">
        <p><a href="{% url 'ecommerce:allProdCat' %}">Home</a> |<a href="{{product.category.get_url}}">{{product.category}}</a>|{{product.name}} </p>
    </div>
</div>
<div class="container" style="padding-bottom:20px;">
<br>
<div class="row">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <div style="min-width:18rem;">
            <img src="{{product.image.url}}" alt="{{product.name}}" style="width:50%;" >
        </div>
    </div>
        <div class="col-12 col-sm-12 col-md-12 col-lg-6">
            <div>
            <h1 class="my_prod_title">{{product.name}}</h1>
            <p>$ {{product.price}}</p><br>
            <p class="my_title">Product Description</p>
            <p class="text-justify my_prod_text">{{product.desc}}</p>
            {% if product.balance <= 0 %}
            <p class="text-justify my_prod_text"><b>OUT OF STOCK</b></p>
            {% else %}
            <a class="btn btn-success" href="{% url 'cart:add_cart' product.id %}">Add to cart</a>
            {% endif %}
                </div>
        </div>

</div>
</div>
{% endblock %}

ecommerceproject/templates/search.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
        Please check Catalogue
{% endblock %}

{% block title %}
        Results -STOCKTON CAFE
{% endblock %}

{% block content %}

<div>
        <p class="text-center my_search_text">You have searched for <b>"{{query}}"</b></p>
</div>
 <div  class="container">
        <div class="row mx-auto" >
            {% for products in products %}
            <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4" style="padding-bottom:50px;">
                <div class="card text-center" style="width:100%;height:100%;">
                    <a href="{{products.get_url}}"><img class="card-img-top my_image" src="{{products.image.url}}" alt="{{products.name}}" style="width:100%;"></a>
                    <div class="card-body">
                        <h4>{{products.name}}</h4>
                        <p>{{products.price}}</p>
                    </div>
                </div>
            </div>
                {% empty %}
                <div class="row mx-auto">
                        <p class="text-center my_search_text">0 results found</p>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}